<?php
/*******************************************************************************
 ** Recurrent Payment request parameters
 * login	20/String	Merchant login name	Mandatory
 * cardrefid	20/String	Equals to card-ref-id obtained in Card Information Reference ID call during Card Registration stage	Mandatory
 * control	128/String	Checksum generated by SHA-1. This is SHA-1 checksum of the concatenation login + client_orderid + cardrefid + amount_in_cents + currency + merchant_control.	Mandatory
 *******************************************************************************/
namespace ariuspay\Gateway\Ariuspay;
use \ariuspay\Gateway\Ariuspay\Exception as ariuspayGatewayAruispayException;
use \ariuspay\Gateway\Ariuspay\Request as Request;
class RecurrentRequest extends Request{
    public function __construct($d){
        parent::__construct([
            "operation" => "make-rebill",
            "fields" => [
				"client_orderid","cardrefid","amount","currency","cvv2","ipaddress","comment","order_desc"
            ],
            "control" => ["login","client_orderid","cardrefid","amount","currency" ,"merchant_control"],
            "data" => $d
        ]);
    }
}
?>
